# permissions for end users to view multiplies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multiply-viewer-role
rules:
- apiGroups:
  - mathops.owlet.today
  resources:
  - multiplies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mathops.owlet.today
  resources:
  - multiplies/status
  verbs:
  - get
