
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mathops.owlet.today
  resources:
  - multiplies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mathops.owlet.today
  resources:
  - multiplies/status
  verbs:
  - get
  - patch
  - update
